name: Django CI

on:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.PASSWORD_TEST }}
          MYSQL_DATABASE: ${{ secrets.NAME_TEST }}
        ports: ['3306:3306']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: python manage.py migrate
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ENGINE: django.db.backends.mysql
        NAME: ${{ secrets.NAME_TEST }}
        USER: root
        PASSWORD: ${{ secrets.PASSWORD_TEST }}
        HOST: ${{ secrets.HOST_TEST }}
        PORT: ${{ job.services.mysql.ports[3306] }}
    - name: Run Tests
      run: |
        python manage.py test
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ENGINE: django.db.backends.mysql
        NAME: ${{ secrets.NAME_TEST }}
        USER: root
        PASSWORD: ${{ secrets.PASSWORD_TEST }}
        HOST: ${{ secrets.HOST_TEST }}
        PORT: ${{ job.services.mysql.ports[3306] }}